import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import InsertWordModal from "../components/InsertWordModal";
import { HomeStyled } from "../components/style/HomeStyle.styles";
import TextInput from "../components/TextInput";
import TimeControl from "../components/TimeControl";
import TimeCountDown from "../components/TimeCountDown";
import WordCloud from "../components/WordCloud";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [activeModal, setActiveModal] = useState(false);
  const [countActive, setCountActive] = useState(false);
  const handleModal = () => {
    setActiveModal(!activeModal);
  };
  return (
    <>
      <Head>
        <title>Typing speed test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeStyled>
        <main>
          <h4>Typing Test</h4>
          <div className="container">
            <header>
              {countActive ? (
                <TextInput />
              ) : (
                <>
                  <TimeControl />
                  <button onClick={handleModal}>Insert your own words</button>
                </>
              )}
            </header>
            <section>
              <WordCloud />
            </section>
            <footer>
              <TimeCountDown />
              <button onClick={() => setCountActive(true)}>Start</button>
            </footer>
          </div>
        </main>
      </HomeStyled>
      {activeModal && <InsertWordModal handleModal={handleModal} />}
    </>
  );
};

export default Home;
